### PR TITLE
Added support for img element rendering

### PR DESCRIPTION
**Pull request by eatskolnikov**

### CODE REVIEW

**Comment by eatskolnikov** [comment]
@justechn the issues mentioned are fixed, is there something missing before merging?

**Comment by justechn** [comment]
@eatskolnikov there are conflicts, please pull the latest and fix the conflicts.

**Comment by eatskolnikov** [comment]
@justechn Fixed the conflicts and pushed

**Comment by eatskolnikov** [comment]
@justechn i added back the examples, sorry, they got away when i was making a merge but now they're back

**Pull request merged**
